version: "3.7"
services:
  server:
    build:
      context: .
    ports:
      - "5005:5005"
    depends_on:
      - db
  db:
    build:
      context: ./db/postgres/schema
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "./db/postgres/schema/backups:/backups"
    environment:
      - POSTGRES_PASSWORD=postgres
      - TZ=Europe/Moscow
    